plugins:
  d_backup_dest_dir:
    default: "/var/discourse/custom_backup"
    client: true
    type: string
    description: "Destination directory to move the backup to"
  d_backup_enable_daily_job:
    default: true
    client: false
    type: bool
    description: "Enable daily backup job"
